### PR TITLE
Rename README to README.md

### PR DESCRIPTION
**Pull request by rmbolger**
This change simply renames README to README.md so Github will render the markdown nicely on the repo homepage.

### CODE REVIEW

**Review by nhairs — CHANGES_REQUESTED** [review]
It looks like this is the wrong location to rename the README. The file is actually generated, see: https://github.com/paulc/dnslib/blob/master/setup.py#L36

**Comment by rmbolger** [comment]
Doesn't `setup.py` only run at install time on the end user's system? So changing it there wouldn't affect what gets committed to the git repo?

**Comment by nhairs** [comment]
Actually it looks like I'm partially mistaken. You'd need to update both the `README` and `setup.py` files.

`setup.py` is somewhat multi-purpose. It will be used in on the "local" machine in source distribution installation, but it can also be used by the maintainer to build wheel or other distributions. Reading [the comments at the top of the file](https://github.com/paulc/dnslib/blob/master/setup.py#L8) it appears it is also being used to generate the README from the package's docstring.

**Comment by paulc** [comment]
Thanks - I've just added a symbolic-link from README -> README.md which seems to fix the problem (and requires minimal changes)

**Comment by rmbolger** [comment]
Nice. I didn't even realize that was possible.

**Pull request closed without merging**
